[package]
name = "rustorgate"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.16", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
socks = "0.3.4"
tokio-util = "0.6"
futures = "0.3"
