[package]
name = "rustorgate"
version = "0.1.2"
edition = "2021"

[dependencies]
tokio = { version = "1.28.0", features = ["full"] }
reqwest = { version = "0.11", features = ["socks"] }
select = "0.6.0"
chrono = "0.4.26"
url = "2.3"
